<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.CommandLine" Version="2.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Orion.Compiler\Orion.Compiler.csproj" />
	</ItemGroup>

</Project>
